/* Header file for function Datastore
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void datastore_startup(void);

/* Provided interfaces */
void datastore_PI_Create( const asn1SccDataType *, asn1SccKeyType * );


void datastore_PI_Delete( const asn1SccKeyType * );


void datastore_PI_Read( const asn1SccKeyType *, asn1SccDataType * );


void datastore_PI_Update( const asn1SccKeyType *, const asn1SccDataType * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
