/* Body file for function Datastore
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "datastore.h"

#include "DataStore.h"
#include "Logs.h"

static DataStore datastore;

void datastore_startup(void)
{
   DataStore_Init(&datastore, 3, false);
}

void datastore_PI_Create(const asn1SccDataType *data, asn1SccKeyType *key)
{
   *key = DataStore_Create(&datastore, *data);
}


void datastore_PI_Delete(const asn1SccKeyType *key )
{
   DataStore_Delete(&datastore, *key);
}


void datastore_PI_Read(const asn1SccKeyType *key, asn1SccDataType *data)
{
   data = DataStore_Read(&datastore, *key);
}


void datastore_PI_Update(const asn1SccKeyType *key, const asn1SccDataType *data)
{
   DataStore_Update(&datastore, *key, *data);
}


