/* Header file for function Environment
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void environment_startup(void);

/* Provided interfaces */
void environment_PI_Trigger( void );

/* Required interfaces */
extern void environment_RI_Create( const asn1SccMyInteger *, asn1SccMyInteger * );


extern void environment_RI_Delete( const asn1SccMyInteger * );


extern void environment_RI_Read( const asn1SccMyInteger *, asn1SccMyInteger * );


extern void environment_RI_Update( const asn1SccMyInteger *, const asn1SccMyInteger * );


#ifdef __cplusplus
}
#endif
