/* Header file for function Environment
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void environment_startup(void);

/* Provided interfaces */
void environment_PI_Trigger( void );


void environment_PI_notify( const asn1SccT_EventMessage * );

/* Required interfaces */
extern void environment_RI_Clean( void );


extern void environment_RI_Create( const asn1SccDataStoreCreateRequect * );


extern void environment_RI_Delete( const asn1SccDataStoreDeleteRequest * );


extern void environment_RI_Retrieve( const asn1SccDataStoreRetrieveRequest * );


extern void environment_RI_RetriveByTimeRange( const asn1SccDataStoreRetrieveTimestampRangeRequest * );


extern void environment_RI_Update( const asn1SccDataStoreUpdateRequest * );


#ifdef __cplusplus
}
#endif
