/* Body file for function Environment
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "environment.h"
#include "logs.h"

#include <time.h>
#include <unistd.h>

#define CUC_TIME_ARRAY_SIZE 7

void environment_startup(void)
{
   asn1SccClockStatusEnum status;
   timeservice_PI_ClockStatus(&status);
   if (status == ClockStatusEnum_available) {
      LOG("Clock status: available\n");
   }
   else if (status == ClockStatusEnum_unavailable) {
      LOG("Clock status: unavailable\n");
   }
}

#define SECONDS_IDX 3

asn1SccCucTimestamp getCucTimestamp()
{
   asn1SccCucTimestamp timestamp;

   asn1SccULongInteger nseconds;
   timeservice_PI_ObetTime(&nseconds);
   timeservice_PI_CucTimestamp(&nseconds, &timestamp);

   return timestamp;
}

void environment_PI_Trigger(void)
{
   asn1SccULongInteger nseconds;
   timeservice_PI_ObetTime(&nseconds);
   LOG_VARIABLE_ENDL("Nanoseconds from start: ", nseconds);

   asn1SccCucTimestamp firstCucTimestamp = getCucTimestamp();
   print_time_array(firstCucTimestamp.arr);
   LOG_VARIABLE_ENDL("First CUC timestamp seconds: ", firstCucTimestamp.arr[SECONDS_IDX]);

   asn1SccCucTimestamp secondCucTimestamp = getCucTimestamp();
   print_time_array(secondCucTimestamp.arr);
   LOG_VARIABLE_ENDL("Second CUC timestamp seconds: ", secondCucTimestamp.arr[SECONDS_IDX]);

   asn1SccComparisonResult compareResultCuc = 0;
   environment_RI_CucTimestampCmp(&secondCucTimestamp, &firstCucTimestamp, &compareResultCuc);
   LOG_VARIABLE_ENDL("CUC timestamps comparison result: ", compareResultCuc);

   asn1SccCfsTimestamp cfsTimestamp1;
   cfsTimestamp1.seconds = 1;
   cfsTimestamp1.subseconds = 300;

   asn1SccCfsTimestamp cfsTimestamp2;
   cfsTimestamp1.seconds = 2;
   cfsTimestamp1.subseconds = 105;

   asn1SccComparisonResult compareResultCfs = 0;
   environment_RI_CfsTimestampCmp(&cfsTimestamp2, &cfsTimestamp1, &compareResultCfs);
   LOG_VARIABLE_ENDL("CFS timestamps comparison result: ", compareResultCfs);

   LOG("\n");
}
